Added docs to README
cadecairos/matterbridge-heroku pull request #5
Opened 2018-11-05 15:35 UTC by patcon

2019-02-12 15:51 UTC, cadecairos requested changes

2019-02-12 15:51 UTC, cadecairos commented on README.md
> +## Related Projects
Thanks for the very detailed documentation! I don't have time to review the projects below, and am not prepared to endorse them without checking first. Can you drop the last section and we'll merge the changes in.

2019-02-13 05:31 UTC, patcon commented on README.md
> +## Related Projects
No prob @cadecairos! Thanks a bunch for making time for review -- life's busy and so I totally appreciate it :)

This section is also present upstream in the matterbridge readme, so I think you're right that it's best to remove

2019-03-13 19:15 UTC, patcon commented
Heh, just realzied it wasn't mergeable, but fixed now. project list removed!

2019-10-04 13:29 UTC, cadecairos approved these changes

2019-10-04 13:29 UTC, merged